In [5]:
import numpy as np

In [7]:
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
print(b[1][1])

5


In [11]:
c = np.zeros((3,3))
print(c)
d = np.ones((2,3))
print(d)
e = np.full((2,3), 5)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]


In [12]:
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
a = np.random.random((2,3))
print(a)

[[0.76309907 0.29459622 0.76617987]
 [0.27643536 0.06667019 0.19960293]]


In [14]:
print(a[ :, 2])

[0.76617987 0.19960293]


In [15]:
print(a[ :, 1])

[0.29459622 0.06667019]


In [17]:
a[1, 1:] = 1
print(a)

[[0.76309907 0.29459622 0.76617987]
 [0.27643536 1.         1.        ]]


In [25]:
z = np.zeros((3,3), dtype = int)

In [26]:
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
z[1, :] = 5
z[ :, -1] = 6

In [21]:
print(z)

[[0. 0. 6.]
 [5. 5. 6.]
 [0. 0. 6.]]


In [28]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [29]:
np.random.shuffle(a)
print(a)

[13 10  6  5  7  9  8 14 11 12]


In [30]:
a = np.random.rand(2,3)
print(a)

[[0.83949979 0.90103059 0.78416279]
 [0.29614507 0.97087974 0.88805374]]


In [31]:
b = np.random.randn(2,3) #normarlized distribution
print(b)

[[-0.17693291  0.31631453 -0.18974492]
 [-1.89969778  0.56803816  0.26117991]]


In [32]:
c = np.random.randint(5,10,3)
print(c)

[7 5 8]


In [34]:
element = np.random.choice([1,2,3,4,5,6,7,8,9,10])
print(element)

7


In [35]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)
print(np.min(a))

[[1 2 3 4]
 [5 6 7 8]]
1
